/**
 * ========================================
 * GAME CONFIGURATION
 * ========================================
 * 
 * Centralized list of games and provider settings.
 * Edit this file to change which games are tested.
 */

export const provider = 'Evoplay';

export const games: string[] = [
  // "Young Buffalo Coins",
  // "Valley of Dreams",
  // "Vegas Nights",
  // "Velvet Games",
  // "Venice Festival",
  // "X-Demon",
  // "X-Demon Bonus Buy",
  // "Young Buffalo Song",
  // "Young Wolf Song",
  // "Unlimited Wishes",
  // "Young Eagle Song",
  // "Hocus Pocus Sorcery",
  // "Trick or Treat Joker",
  // "Young Deer Song",
  // "Mega Greatest Catch Blue Marlin",
  // "Sunstone Riches",
  // "Train of Riches: Capital Express",
  // "Three Trojan Horses",
  // "Treasure-snipes: Christmas",
  // "Wonder Farm",
  // "Wolf Hiding Bonus Buy",
  // "Wolf Hiding",
  // "Winter Star Bonus Buy",
  // "Winter Star",
  // "Treasure Mania",
  // "Treasure-Snipes",
  // "Treasure-snipes Bonus Buy",
  // "Hot Rio Samba",
  // "Treasure-snipes: Christmas Bonus Buy",
  // "Tree of Light",
  // "Tree Of Light Bonus Buy",
  // "Tree of Light: Fabled Fruits",
  // "Triple Chili",
  // "Unlimited Treasures",
  // "Dungeon Immortal Evil",
  // "Unlimited Treasures Bonus Buy",
  // "Love and Luck Joker",
  // "Wild Bullets",
  // "Wild Overlords",
  // "Wild Overlords Bonus Buy",
  // "Wild Pounce",
  // "Wonder Farm Bonus Buy",
  // "Queen of Sirens",
  // "Pyro Joker",
  // "Piggy Bank: 3 Pots Bonanza",
  // "Ocean Catch Bonus Buy",
  // "Oath of Steel",
  // "Reign Of Dragons",
  // "Rich Reels",
  // "Rise of Horus",
  // "Nuke World",
  // "Northern Temple Bonus Buy",
  // "Northern Temple",
  // "Neon Capital Bonus Buy",
  // "Money Minter Bonus Buy",
  // "Money Minter",
  // "Mega Merry Gifts",
  // "Mega Greatest Catch Bonus Buy",
  // "Mega Greatest Catch",
  // "Massive Luck Bonus Buy",
  // "Massive Luck",
  // "Lunar Wilds",
  // "Lucky Porker Bonus Buy",
  // "Robin Hood",
  // "Rocket Stars",
  "Roman Rule",
  "Rueda De Chile",
  "Rueda De Chile Bonus Buy",
  "Rush Riches",
  "Sea of Wealth"
];
